# Development file for docker compose.

version: "3.9"

services:
  server:
    container_name: server
    image: golang:1.13-alpine
    depends_on: 
      - database
    env_file: 
      - .env.dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  database:
    container_name: database
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: GO_AUTH_DB